Partially revert commit a9e5008
This commit fixes this from happening on running a edl command without rebooting the device on every command:

```
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2024.
main - Using loader 0000000000000000_b01193679ab2eac7_fhprg_peek.bin ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: firehose
Traceback (most recent call last):
  File "/usr/local/bin/edl", line 393, in <module>
    base.run()
  File "/usr/local/bin/edl", line 295, in run
    version = conninfo.get("data").version
AttributeError: 'NoneType' object has no attribute 'version'
root@HP-PAVILION-590:~#
```

Signed-off-by: Christopher Lentocha <christopherericlentocha@gmail.com>