Fix qfp & pbl dump support on APQ8009w
The "w" at the end, HAS to be a lower case "w", due to "TargetName=MSM8909w", rename it from "W" to "w" to fix that.
Add APQ8009w to pbl dumping with a "w" loader (a non-"w" loader would work but it would show as "APQ8009" instead of "APQ8009w")
What is the mention of Wear3100 still doing in here? Remove that, as Wear2100 is the same as that, but it should be called by chipset anyways.
Also, the Snapdragon 212 is actually a "MSM8909v2" (note the v2).
PBL dumping doesn't however fully work on my mobvoi-catfish, it gets to 75%, and reboots, no matter what loader I use.

```

Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2024.
main - Using loader /Loaders/qualcomm/model_generic/msm8909w/0000000000000000_b01193679ab2eac7_fhprg_peek.bin ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara -
Version 0x2
------------------------
HWID:              0x000520e100000000 (MSM_ID:0x000520e1,OEM_ID:0x0000,MODEL_ID:0x0000)
CPU detected:      "APQ8009w"
PK_HASH:           0xcc3153a80293939b90d02d3bf8b23e0292e452fef662c74998421adad42a380f
Serial:            0x16e0f376

sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader /Loaders/qualcomm/model_generic/msm8909w/0000000000000000_b01193679ab2eac7_fhprg_peek.bin ...
sahara - 32-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
main - Trying to connect to firehose loader ...
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose
firehose - [LIB]: !DEBUG! rsp.data: 'bytearray(b'<?xml version="1.0" encoding="UTF-8" ?><data><log value="logbuf@0x080548D0 fh@0x08051738" /></data>')'
firehose - TargetName=MSM8909w
firehose - MemoryName=eMMC
firehose - Version=1
firehose - Trying to read first storage sector...
firehose - Running configure...
firehose_client - Supported functions:
-----------------
firehose - Peek: Address(0x100000),Size(0x1ffb0)
Progress: |██████████████████████████████████████------------|  75.0% Complete                                                                                                                                   DeviceClass - USBError(5, 'Input/Output Error')
Traceback (most recent call last):
  File "/home/ce1cecl/edl/./edl", line 393, in <module>
    base.run()
  File "/home/ce1cecl/edl/./edl", line 385, in run
    if not fh.handle_firehose(cmd, options):
  File "/home/ce1cecl/edl/edlclient/Library/firehose_client.py", line 397, in handle_firehose
    if self.firehose.cmd_peek(target_name[0][0], target_name[0][1], filename, True):
  File "/home/ce1cecl/edl/edlclient/Library/firehose.py", line 1682, in cmd_peek
    rdata = self.xml.getlog(tmp)[0].replace("0x", "").replace(" ", "")
IndexError: list index out of range
root@LenovoLegionT5:/home/ce1cecl/edl#

```

Signed-off-by: Christopher Lentocha <christopherericlentocha@gmail.com>